name: deploy
on:
  push:
    tags:
    - '*'
jobs:
  publish-linux-arm64:
    runs-on: ubuntu-22.04-arm
    container:
      image: alpine:latest
    steps:
      - name: deps
        run: apk add git make cmake automake libtool ruby build-base clang alsa-lib-dev eudev-dev jack-dev libdecor-dev libsamplerate-dev libusb-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxkbcommon-dev libxrandr-dev libxrender-dev libxscrnsaver-dev libxtst-dev pipewire-dev pulseaudio-dev samurai wayland-dev wayland-protocols mesa-dev
      - uses: laverdet/alpine-arm64@v1
      - uses: actions/checkout@v5
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'skinnyjames/mruby-bin-barista'
          version: 'tags/0.3.1'
          file: 'barista-linux-arm64.tar.gz'
          target: 'barista.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: unpack barista
        run: tar -xvf barista.tar.gz --strip-components 1
      - name: gem install rake
        run: gem install rake
      - name: build pocket
        run: chmod 755 barista && ./barista @mobile
      - uses: actions/upload-artifact@v4
        with:
          name: hokusai-pocket-linux-arm64
          path: bin/hokusai-pocket
          overwrite: true
  publish-linux:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: deps
        run: apt-get update -y && apt-get install -y git wget cmake automake libtool ruby clang build-essential libasound2-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxi-dev libxrandr-dev mesa-common-dev xorg-dev
      - uses: actions/checkout@v5
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'skinnyjames/mruby-bin-barista'
          version: 'tags/0.3.1'
          file: 'barista-linux-x86.tar.gz'
          target: 'barista.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: unpack barista
        run: tar -xvf barista.tar.gz --strip-components 1
      - name: build pocket
        run: chmod 755 barista && ./barista @desktop
      - uses: actions/upload-artifact@v4
        with:
          name: hokusai-pocket-linux
          path: bin/hokusai-pocket
          overwrite: true
  publish-osx:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v5
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'skinnyjames/mruby-bin-barista'
          version: 'tags/0.3.1'
          file: 'barista-osx-x86.tar.gz'
          target: 'barista.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: unpack barista
        run: tar -xvf barista.tar.gz --strip-components 1
      - name: deps
        run: brew install automake
      - name: build pocket
        run: chmod 755 barista && ./barista @desktop
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: hokusai-pocket-osx
          path: bin/hokusai-pocket*
          overwrite: true
  publish-windows:
    runs-on: ubuntu-latest
    container:
      image: skinnyjames/mruby-cross-windows:latest
    steps:
      - uses: actions/checkout@v5
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'skinnyjames/mruby-bin-barista'
          version: 'tags/0.3.1'
          file: 'barista-linux-x86.tar.gz'
          target: 'barista.tar.gz'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: unpack barista
        run: tar -xvf barista.tar.gz --strip-components 1
      - name: cmake
        run: apt update -y && apt install -y cmake wget
      - name: build pocket
        env:
          AR: x86_64-w64-mingw32-ar
          GCC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++
          CMAKE: cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ -DCMAKE_FIND_ROOT_PATH=/usr/x86_64-w64-mingw32
          MINGW: true
        run: chmod 755 barista && ./barista @desktop
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: hokusai-pocket-windows
          path: bin/hokusai-pocket*
          overwrite: true
  release:
    needs: [publish-linux, publish-linux-arm64, publish-windows, publish-osx]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: hokusai-pocket*
    - name: zip artifacts
      run: |
        tar -czvf hokusai-pocket-x86-linux.tar.gz hokusai-pocket-linux
        tar -czvf hokusai-pocket-arm64-linux.tar.gz hokusai-pocket-linux-arm64
        tar -czvf hokusai-pocket-x86-osx.tar.gz hokusai-pocket-osx
        tar -czvf hokusai-pocket-x86-windows.tar.gz hokusai-pocket-windows
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "hokusai-pocket*"
